### ISSUE TITLE
error :  No such file or directory: control/NA10851.mat

### ISSUE THREAD

**Issue by gpcr** [buske/silva#4]
I have just installed silva and ran the 

./silva-preprocess TMP example/example.vcf 

Iam getting below error 
Can you help to fix it 
thanks

```
...
Running: 0_gerp.col
Loading optimized table from: /git/silva/silva-1.1.1/data/gerp.refGene.pkl
Completed: cpg.col
Completed: codon.col
Completed: splice.col
Completed: fas-ess.col
Completed: pesx.col
Completed: ese3.col
Completed: maxent.col
Completed: 0_gerp.col
Running: unafold-50.col
Running: vienna-50.col
Completed: unafold-50.col
Completed: vienna-50.col
Standardizing MAT file according to control data...
Traceback (most recent call last):
  File "/git/silva/silva-1.1.1/src/input/standardize.py", line 134, in <module>
    sys.exit(main())
  File "/git/silva/silva-1.1.1/src/input/standardize.py", line 131, in main
    script(*args, **kwargs)
  File "/git/silva/silva-1.1.1/src/input/standardize.py", line 82, in script
    control_header, control_class_col, control = read_examples(control)
  File "/git/silva/silva-1.1.1/src/input/standardize.py", line 29, in read_examples
    with maybe_gzip_open(filename) as ifp:
  File "/git/silva/silva-1.1.1/lib/python/silva/__init__.py", line 16, in maybe_gzip_open
    return open(filename, *args, **kwargs)
IOError: [Errno 2] No such file or directory: '/git/silva/silva-1.1.1/control/NA10851.mat'

```

**Comment by buske** [comment]
@gpcr Thanks for pointing this out! It looks like the control file and pre-trained model were in the tar distribution but didn't make it into VCS. I've added these to the repo, so if you pull you should get them! I'm going to close this issue, but please feel free to re-open or create a new one if there are still problems.

**Comment by buske** [comment]
Also, it looks like you're using the rna folding features, so make sure you set EXCLUDE_RNA_FOLDING accordingly after pulling. The default behaviour changed, and rna folding features are now excluded, in part because unafold is not openly downloadable anymore.
