### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '18080854\xc2\xa0'

### ISSUE THREAD

**Issue by martielafreitas** [buske/silva#8]
This is the first time I faced an error with SilVA. Anyone to help me?

`Saving genes to pickled file: /home/martiela/Bioinformatica/SilVA/silva-1.1.1-nofolding/data/refGene.pkl
Traceback (most recent call last):

  File "/home/martiela/Bioinformatica/SilVA/silva-1.1.1-nofolding/src/input/synonymous.py", line 843, in <module>
    sys.exit(main())

  File "/home/martiela/Bioinformatica/SilVA/silva-1.1.1-nofolding/src/input/synonymous.py", line 840, in main
    script(*args, **kwargs)

  File "/home/martiela/Bioinformatica/SilVA/silva-1.1.1-nofolding/src/input/synonymous.py", line 699, in script
    filter_variants(genes, filename, protein_coords=protein_coords)

  File "/home/martiela/Bioinformatica/SilVA/silva-1.1.1-nofolding/src/input/synonymous.py", line 635, in filter_variants
    pos = int(pos)

ValueError: invalid literal for int() with base 10: '18080854\xc2\xa0'
`

**Comment by buske** [comment]
Hi @martielafreitas, it looks like your input file has a non-breaking space (utf-8 literal: \xc2\xa0) after the position (18080854) on that line. The columns in the input file should be separated by tabs.

**Comment by martielafreitas** [comment]
True! I have a nbsp at the end of one of my lines.
Thanks a lot!
